### ISSUE TITLE
Error with Linux/arm build

### ISSUE THREAD

**Issue by uihdff** [jedisct1/dnscrypt-proxy-installer#2]
Platform: Asus RT-AC88U running Asuswrt-Merlin 380.65.

When running the following command ...

`/opt/dnscrypt-proxy/arm-linux-musleabi/bin/dnscrypt-proxy /opt/dnscrypt-proxy/arm-linux-musleabi/etc/dnscrypt-proxy.conf`

... the following error occurs.

`env: can't execute '/opt/dnscrypt-proxy/arm-linux-musleabi/.sw/dnscrypt-proxy/sbin/dnscrypt-proxy': No such file or directory`

**Comment by jedisct1** [comment]
Does the file exist?

**Comment by uihdff** [comment]
@jedisct1,

1) I don't know if it matters, but at the beginning of the extracted files, there's a space character in the shebang.

`#! /bin/sh`

2) I don't understand this line in the "/opt/dnscrypt-proxy/arm-linux-musleabi/bin/dnscrypt-proxy" file.

`exec env PATH="/opt/dnscrypt-proxy/arm-linux-musleabi/bin:/usr/local/opt/curl/bin:/Users/j/.rvm/gems/ruby-2.3.0/bin:/Users/j/.rvm/gems/ruby-2.3.0@global/bin:/Users/j/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/opt/openssh/bin:/opt/openssh/sbin:/opt/libtool/bin:/Users/j/pear/bin:/usr/local/share/npm/bin:/opt/rust/bin:/Users/j/go/bin:/opt/infer/infer/infer/bin:/Users/j/.cargo/bin:/Users/j/go/bin:/Users/j/.rvm/bin:/opt/coverity/bin:/opt/dnstap/bin:/opt/ldns/bin:/opt/rust/bin:/opt/vagrant/bin" LD_LIBRARY_PATH="/opt/dnscrypt-proxy/arm-linux-musleabi/.sw/libsodium/lib:/opt/dnscrypt-proxy/arm-linux-musleabi/.sw/ldns/lib:" '/opt/dnscrypt-proxy/arm-linux-musleabi/.sw/dnscrypt-proxy/sbin/dnscrypt-proxy' $*`

**Comment by jedisct1** [comment]
Can you try to run the installer with `bash ./installer.sh` instead?
What filesystem are you using?

**Comment by uihdff** [comment]
Same error with bash.

The output of `df-T`

Filesystem | Type
--------------- | ---------
rootfs | rootfs
/dev/root | squashfs
devtmpfs | devtmpfs
tmpfs | tmpfs
/dev/mtdblock4 | jffs2
/dev/sda1 | t4

**Comment by jedisct1** [comment]
Sorry, I don't know what's going on.

But you can manually move the `.sw` folder extracted from the archive to `/opt/dnscrypt-proxy/arm-linux-musleabi/`

**Comment by uihdff** [comment]
When I look at the file structure in WinSCP and Putty, the /.sw folder isn't visible. But when I attempt to create a ".sw" folder, WinSCP reports that it already exists.

![scp](https://cloud.githubusercontent.com/assets/22044303/25583799/6e75ca2e-2e61-11e7-9e9a-a260417b128e.jpg)

The problem appears to be due to folders whose name begins with a period.

Is it a problem if these folders aren't prefixed with a period ?

**Comment by uihdff** [comment]
Just noticed this error.

After running /tmp/mnt/sda1/test/dnscrypt-proxy# ./installer.sh

`mv: can't create '/lib/ld-musl-arm.so.1': Read-only file system`

**Comment by jedisct1** [comment]
Wait, what? What do WinSCP and Putty have to do with it? You should extract the archive on the system itself.

**Comment by jedisct1** [comment]
Remount the partition so that it can be written.

```sh
mount -o remount,rw /
```

**Comment by uihdff** [comment]
The files were extracted on the router.

`tar -xzf ?dnscrypt-proxy-arm-linux-musleabi.tar.gz`

You asked whether the file existed.

I only mentioned WinSCP and Putty due to not seeing the /.sw folder. After enabling WinSCP to display hidden files, the /.sw folder is visible. Using ls -la in Putty also shows the /.sw folder. After that, I deleted the comment mentioning WinSCP and Putty.

**Comment by uihdff** [comment]
With Asuswrt-Merlin, tThe /lib directory is stored on read-only flash.

Is there a way to relocate the modifications to the /lib directory to another location like /mnt/sda1 ?

**Comment by jedisct1** [comment]
Unfortunately, that file has to be in `/lib`.

You can use a `chroot` jail to work around it, but it's going to make things more complicated since all paths in the configuration file will be relative to the new root.

**Comment by uihdff** [comment]
If /lib has to be read/write, then Asuswrt or Asuswrt-Merlin can't use this type of installer.

I'm curious as to how the Entware-NG developers managed to avoid this issue with their build of dnscrypt-proxy.

**Comment by jedisct1** [comment]
chroot()ing has no performance implications. But you need to be careful about the paths used in the config file, including paths to log files.
