### ISSUE TITLE
Example systemd service file is missing an Install section

### ISSUE THREAD

**Issue by kensfc-23** [jedisct1/dnscrypt-proxy-installer#3]
_Hello, I use Ubuntu Gnome 17.04_

_I have installed dnscrypt-proxy with this installer and I get this:_

Installed:

/opt/dnscrypt-proxy/x86_64-linux-musl/bin/hostip
/opt/dnscrypt-proxy/x86_64-linux-musl/bin/minisign
/opt/dnscrypt-proxy/x86_64-linux-musl/bin/dnscrypt-update-resolvers.sh
/opt/dnscrypt-proxy/x86_64-linux-musl/bin/dnscrypt-proxy
/opt/dnscrypt-proxy/x86_64-linux-musl/etc/dnscrypt-proxy.conf

**You may want to add "/opt/dnscrypt-proxy/x86_64-linux-musl/bin/" to your /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin variable.**

For testing, the proxy can be started with:
/opt/dnscrypt-proxy/x86_64-linux-musl/bin/dnscrypt-proxy /opt/dnscrypt-proxy/x86_64-linux-musl/etc/dnscrypt-proxy.conf

_It works:_

Thu May  4 21:51:54 2017 [INFO] Randomly chosen resolver: [d0wn-tz-ns1]
Thu May  4 21:51:54 2017 [INFO] + DNS Security Extensions are supported
Thu May  4 21:51:54 2017 [INFO] + Provider supposedly doesn't keep logs
Thu May  4 21:51:54 2017 [NOTICE] Starting dnscrypt-proxy 1.9.4
Thu May  4 21:51:54 2017 [INFO] Loading plugin [/opt/dnscrypt-proxy/x86_64-linux-musl/.sw/dnscrypt-proxy/lib/dnscrypt-proxy/libdcplugin_example_cache.so]
Thu May  4 21:51:54 2017 [INFO] Loaded plugin: [A basic DNS cache]
Thu May  4 21:51:54 2017 [INFO] Generating a new session key pair
Thu May  4 21:51:54 2017 [INFO] Done
Thu May  4 21:51:54 2017 [INFO] Server certificate with serial #1493920861 received
Thu May  4 21:51:54 2017 [INFO] This certificate is valid
Thu May  4 21:51:54 2017 [INFO] Chosen certificate #1493920861 is valid from [2017-05-04] to [2017-05-05]
Thu May  4 21:51:54 2017 [INFO] Server key fingerprint is E15C:C17C:02A5:4C3F:FDAB:5D64:2204:307A:0812:FD67:5095:B801:741F:AC50:72EB:1467
Thu May  4 21:51:54 2017 [NOTICE] Proxying from 127.0.0.1:53 to 41.79.69.13:443

How can I create a systemd service to run it permanently?

**Comment by kensfc-23** [comment]
I have created a file "/etc/systemd/system/dnscrypt-proxy.service"

I enter "sudo systemctl enable dnscrypt-proxy" and I get this:

The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.

**Comment by jedisct1** [comment]
Ah, maybe an `Install` section is actually needed :) Sorry for that.

I updated the example in the `README` file in order to add this section.

Thanks!

**Comment by kensfc-23** [comment]
Thank you Frank
