### ISSUE TITLE
.sw/dnscrypt-proxy/sbin/dnscrypt-proxy: No such file or directory

### ISSUE THREAD

**Issue by rizalp** [jedisct1/dnscrypt-proxy-installer#5]
I could not start dnscrypt proxy either from systemd or from command line. `journalctl` log shows:

```
Aug 08 09:42:34 l420 systemd[1]: Started DNSCrypt client proxy.
Aug 08 09:42:34 l420 dnscrypt-proxy[10079]: env: ‘/opt/dnscrypt-proxy/x86_64-linux-musl/.sw/dnscrypt-proxy/sbin/dnscrypt-proxy’: No such file or directory
Aug 08 09:42:34 l420 systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=127/n/a
Aug 08 09:42:34 l420 systemd[1]: dnscrypt-proxy.service: Unit entered failed state.
Aug 08 09:42:34 l420 systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
```

Could be there's some link missing in that file? I'm using https://download.dnscrypt.org/dnscrypt-proxy/binaries/linux/dnscrypt-proxy-x86_64-linux-musl.tar.gz

**Comment by jedisct1** [comment]
Does the file `/opt/dnscrypt-proxy/x86_64-linux-musl/.sw/dnscrypt-proxy/sbin/dnscrypt-proxy` actually exist?

**Comment by jedisct1** [comment]
Ah, no, it looks like the libc hasn't been included in the packages due to an update of musl-cross.

Very sorry for that.

I'll try to build update packages soon.

**Comment by rizalp** [comment]
Thanks for the response! I'll wait for the build

**Comment by jedisct1** [comment]
Alternatively you can install the musl-libc package (or whatever it's called in your distribution).

**Comment by jedisct1** [comment]
The binaries were updated.

Thanks!
